SELECT
  BOOL_AND(id IS NOT NULL) AS id,

  BOOL_AND(customer_first_name <> '' AND customer_first_name IS NOT NULL)   AS customer_first_name,
  BOOL_AND(customer_last_name  <> '' AND customer_last_name  IS NOT NULL)   AS customer_last_name,
  BOOL_AND(customer_age        IS NOT NULL)                                 AS customer_age,
  BOOL_AND(customer_email      <> '' AND customer_email      IS NOT NULL)   AS customer_email,
  BOOL_AND(customer_country    <> '' AND customer_country    IS NOT NULL)   AS customer_country,
  BOOL_AND(customer_postal_code<> '' AND customer_postal_code IS NOT NULL)   AS customer_postal_code,

  BOOL_AND(customer_pet_type    <> '' AND customer_pet_type    IS NOT NULL)  AS customer_pet_type,
  BOOL_AND(customer_pet_name    <> '' AND customer_pet_name    IS NOT NULL)  AS customer_pet_name,
  BOOL_AND(customer_pet_breed   <> '' AND customer_pet_breed   IS NOT NULL)  AS customer_pet_breed,
  BOOL_AND(pet_category         <> '' AND pet_category         IS NOT NULL)  AS pet_category,

  BOOL_AND(seller_first_name    <> '' AND seller_first_name    IS NOT NULL)  AS seller_first_name,
  BOOL_AND(seller_last_name     <> '' AND seller_last_name     IS NOT NULL)  AS seller_last_name,
  BOOL_AND(seller_email         <> '' AND seller_email         IS NOT NULL)  AS seller_email,
  BOOL_AND(seller_country       <> '' AND seller_country       IS NOT NULL)  AS seller_country,
  BOOL_AND(seller_postal_code   <> '' AND seller_postal_code   IS NOT NULL)  AS seller_postal_code,

  BOOL_AND(supplier_name        <> '' AND supplier_name        IS NOT NULL)  AS supplier_name,
  BOOL_AND(supplier_contact     <> '' AND supplier_contact     IS NOT NULL)  AS supplier_contact,
  BOOL_AND(supplier_email       <> '' AND supplier_email       IS NOT NULL)  AS supplier_email,
  BOOL_AND(supplier_phone       <> '' AND supplier_phone       IS NOT NULL)  AS supplier_phone,
  BOOL_AND(supplier_address     <> '' AND supplier_address     IS NOT NULL)  AS supplier_address,
  BOOL_AND(supplier_city        <> '' AND supplier_city        IS NOT NULL)  AS supplier_city,
  BOOL_AND(supplier_country     <> '' AND supplier_country     IS NOT NULL)  AS supplier_country,

  BOOL_AND(store_name           <> '' AND store_name           IS NOT NULL)  AS store_name,
  BOOL_AND(store_location       <> '' AND store_location       IS NOT NULL)  AS store_location,
  BOOL_AND(store_city           <> '' AND store_city           IS NOT NULL)  AS store_city,
  BOOL_AND(store_state          <> '' AND store_state          IS NOT NULL)  AS store_state,
  BOOL_AND(store_country        <> '' AND store_country        IS NOT NULL)  AS store_country,
  BOOL_AND(store_phone          <> '' AND store_phone          IS NOT NULL)  AS store_phone,
  BOOL_AND(store_email          <> '' AND store_email          IS NOT NULL)  AS store_email,

  BOOL_AND(product_name         <> '' AND product_name         IS NOT NULL)  AS product_name,
  BOOL_AND(product_category     <> '' AND product_category     IS NOT NULL)  AS product_category,
  BOOL_AND(product_price        IS NOT NULL)                                 AS product_price,
  BOOL_AND(product_quantity     IS NOT NULL)                                 AS product_quantity,
  BOOL_AND(product_weight       IS NOT NULL)                                 AS product_weight,
  BOOL_AND(product_color        <> '' AND product_color        IS NOT NULL)  AS product_color,
  BOOL_AND(product_size         <> '' AND product_size         IS NOT NULL)  AS product_size,
  BOOL_AND(product_brand        <> '' AND product_brand        IS NOT NULL)  AS product_brand,
  BOOL_AND(product_material     <> '' AND product_material     IS NOT NULL)  AS product_material,
  BOOL_AND(product_description  <> '' AND product_description  IS NOT NULL)  AS product_description,
  BOOL_AND(product_rating       IS NOT NULL)                                 AS product_rating,
  BOOL_AND(product_reviews      IS NOT NULL)                                 AS product_reviews,
  BOOL_AND(product_release_date IS NOT NULL)                                 AS product_release_date,
  BOOL_AND(product_expiry_date  IS NOT NULL)                                 AS product_expiry_date,

  BOOL_AND(sale_date            IS NOT NULL)                                 AS sale_date,
  BOOL_AND(sale_customer_id     IS NOT NULL)                                 AS sale_customer_id,
  BOOL_AND(sale_seller_id       IS NOT NULL)                                 AS sale_seller_id,
  BOOL_AND(sale_product_id      IS NOT NULL)                                 AS sale_product_id,
  BOOL_AND(sale_quantity        IS NOT NULL)                                 AS sale_quantity,
  BOOL_AND(sale_total_price     IS NOT NULL)                                 AS sale_total_price
FROM mock_data_raw;
