SELECT
  COUNT(*) = COUNT(DISTINCT id)                            AS id_unique,

  COUNT(*) = COUNT(DISTINCT customer_first_name)           AS customer_first_name_unique,
  COUNT(*) = COUNT(DISTINCT customer_last_name)            AS customer_last_name_unique,
  COUNT(*) = COUNT(DISTINCT customer_age)                  AS customer_age_unique,
  COUNT(*) = COUNT(DISTINCT customer_email)                AS customer_email_unique,
  COUNT(*) = COUNT(DISTINCT customer_country)              AS customer_country_unique,
  COUNT(*) = COUNT(DISTINCT customer_postal_code)          AS customer_postal_code_unique,
  COUNT(*) = COUNT(DISTINCT customer_pet_type)             AS customer_pet_type_unique,
  COUNT(*) = COUNT(DISTINCT customer_pet_name)             AS customer_pet_name_unique,
  COUNT(*) = COUNT(DISTINCT customer_pet_breed)            AS customer_pet_breed_unique,
  COUNT(*) = COUNT(DISTINCT pet_category)                  AS pet_category_unique,

  COUNT(*) = COUNT(DISTINCT seller_first_name)             AS seller_first_name_unique,
  COUNT(*) = COUNT(DISTINCT seller_last_name)              AS seller_last_name_unique,
  COUNT(*) = COUNT(DISTINCT seller_email)                  AS seller_email_unique,
  COUNT(*) = COUNT(DISTINCT seller_country)                AS seller_country_unique,
  COUNT(*) = COUNT(DISTINCT seller_postal_code)            AS seller_postal_code_unique,

  COUNT(*) = COUNT(DISTINCT supplier_name)                 AS supplier_name_unique,
  COUNT(*) = COUNT(DISTINCT supplier_contact)              AS supplier_contact_unique,
  COUNT(*) = COUNT(DISTINCT supplier_email)                AS supplier_email_unique,
  COUNT(*) = COUNT(DISTINCT supplier_phone)                AS supplier_phone_unique,
  COUNT(*) = COUNT(DISTINCT supplier_address)              AS supplier_address_unique,
  COUNT(*) = COUNT(DISTINCT supplier_city)                 AS supplier_city_unique,
  COUNT(*) = COUNT(DISTINCT supplier_country)              AS supplier_country_unique,

  COUNT(*) = COUNT(DISTINCT store_name)                    AS store_name_unique,
  COUNT(*) = COUNT(DISTINCT store_location)                AS store_location_unique,
  COUNT(*) = COUNT(DISTINCT store_city)                    AS store_city_unique,
  COUNT(*) = COUNT(DISTINCT store_state)                   AS store_state_unique,
  COUNT(*) = COUNT(DISTINCT store_country)                 AS store_country_unique,
  COUNT(*) = COUNT(DISTINCT store_phone)                   AS store_phone_unique,
  COUNT(*) = COUNT(DISTINCT store_email)                   AS store_email_unique,

  COUNT(*) = COUNT(DISTINCT product_name)                  AS product_name_unique,
  COUNT(*) = COUNT(DISTINCT product_category)              AS product_category_unique,
  COUNT(*) = COUNT(DISTINCT product_price)                 AS product_price_unique,
  COUNT(*) = COUNT(DISTINCT product_quantity)              AS product_quantity_unique,
  COUNT(*) = COUNT(DISTINCT product_weight)                AS product_weight_unique,
  COUNT(*) = COUNT(DISTINCT product_color)                 AS product_color_unique,
  COUNT(*) = COUNT(DISTINCT product_size)                  AS product_size_unique,
  COUNT(*) = COUNT(DISTINCT product_brand)                 AS product_brand_unique,
  COUNT(*) = COUNT(DISTINCT product_material)              AS product_material_unique,
  COUNT(*) = COUNT(DISTINCT product_description)           AS product_description_unique,
  COUNT(*) = COUNT(DISTINCT product_rating)                AS product_rating_unique,
  COUNT(*) = COUNT(DISTINCT product_reviews)               AS product_reviews_unique,
  COUNT(*) = COUNT(DISTINCT product_release_date)          AS product_release_date_unique,
  COUNT(*) = COUNT(DISTINCT product_expiry_date)           AS product_expiry_date_unique,

  COUNT(*) = COUNT(DISTINCT sale_date)                     AS sale_date_unique,
  COUNT(*) = COUNT(DISTINCT sale_customer_id)              AS sale_customer_id_unique,
  COUNT(*) = COUNT(DISTINCT sale_seller_id)                AS sale_seller_id_unique,
  COUNT(*) = COUNT(DISTINCT sale_product_id)               AS sale_product_id_unique,
  COUNT(*) = COUNT(DISTINCT sale_quantity)                 AS sale_quantity_unique,
  COUNT(*) = COUNT(DISTINCT sale_total_price)              AS sale_total_price_unique

FROM mock_data_raw;
